from .client import ClientCreate,ClientMinimalRead,ClientRead,ClientUpdate
from .employee import EmployeeCreate,EmployeeMinimalRead,EmployeeRead,EmployeeUpdate
from .inventory_movements import InventoryMovementCreate,InventoryMovementMinimalRead,InventoryMovementRead,InventoryMovementUpdate
from .order_product import OrderProductCreate,OrderProductMinimalRead,OrderProductRead,OrderProductUpdate
from .order_service import OrderServiceCreate,OrderServiceMinimalRead,OrderServiceRead,OrderServiceUpdate
from .product import ProductCreate,ProductMinimalRead,ProductRead,ProductUpdate
from .service import ServiceCreate,ServiceMinimalRead,ServiceRead,ServiceUpdate
from .user import UserCreate,UserMinimalRead,UserRead, UserUpdate
from .vehicle import VehicleCreate,VehicleRead,VehicleUpdate,VehicleMinimalRead
from .comment import CommentCreate,CommentMainResponse,CommentReplyResponse
from .auth import LoginRequest

ClientRead.model_rebuild()
VehicleRead.model_rebuild()
VehicleMinimalRead.model_rebuild()